services:
  php-apache:
    container_name: php-apache
    build:
      dockerfile: php-dockerfile
      context: .
    restart: always
    volumes:
      - './html:/var/www/html'
    ports:
      - 80:80
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: password
    networks:
      - containers
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    volumes:
      - './postgres-db-volume:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    networks:
      - containers
networks:
  containers:
    name: containers
    driver: bridge