services:
  web:
    image: php:apache
    ports:
      - "80:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: db-password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: user-password
    volumes:
      - ./mysql-data:/var/lib/mysql