<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Connecting to a Database via PHP</title>
</head>
<body>
    <h1>Trying to connect to the local database...</h1>
    <?php
        echo "<p>This content is generated by PHP.</p>";
        $name = "User";
        echo "<p>Hello, " . $name . "!</p>";
    ?>
</body>
</html>